### PR TITLE
chore: git hooks

### PR DESCRIPTION
**Pull request by cv65kr**
# Reason for This PR

Improve DX

## Description of Changes

Added git hooks

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the MIT license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

### CODE REVIEW

**Comment by rustatian** [comment]
Hey @cv65kr 👋🏻 Mooooore git hooks 😃 
Could you please update the script to be the same as here (I updated it a little): https://github.com/roadrunner-server/roadrunner/blob/master/.githooks/pre-commit

**Comment by cv65kr** [comment]
Will update a bit later. When I am working on some plugin trying to add hooks as well 😀

**Comment by cv65kr** [comment]
@rustatian updated

**Review by rustatian — APPROVED** [review]
lgtm

**Comment by rustatian** [comment]
Thanks @cv65kr 👍🏻

**Pull request merged**
